# Generated by Django 3.0.5 on 2020-04-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='price',
        ),
        migrations.AddField(
            model_name='size',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
