# Generated by Django 3.0.5 on 2020-04-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
