# Generated by Django 3.0.5 on 2020-04-11 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200410_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pub_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='game/images'),
        ),
    ]
