# Generated by Django 3.0.5 on 2020-04-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20200424_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ecom1name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='ecom2name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='ecom3name',
            field=models.URLField(default='', max_length=250),
        ),
    ]
