# Generated by Django 3.0.5 on 2020-04-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20200424_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ecom3name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
