# Generated by Django 3.0.5 on 2020-04-19 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0010_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='user',
        ),
        migrations.AddField(
            model_name='design',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
