# Generated by Django 3.0.5 on 2020-04-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20200424_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=60)),
                ('detail', models.CharField(default='', max_length=500)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
