# Generated by Django 3.0.5 on 2020-04-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_notify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='title',
            new_name='purpose',
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='happy',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
