# Generated by Django 3.0.5 on 2020-04-20 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0011_auto_20200419_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_name', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='game/images')),
                ('happylikes', models.ManyToManyField(blank=True, related_name='happylikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
