# Generated by Django 3.0.5 on 2020-04-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20200427_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sdesc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='product',
            name='feat',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
