"""
Django settings for gamobysite project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'zx#qork17i=@z(n*6thl&1b0t(j^iy1j2hqda48fry4jcyqu^p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['gamoby.herokuapp.com']


# Application definition

INSTALLED_APPS = [
    'game',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'cloudinary',
    'storages',
    'import_export',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gamobysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gamobysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'GAMOBY_TEST',
#         'USER':'postgres',
#         'PASSWORD':'focus@onme',
#         'HOST':'localhost',
#         'PORT':'5432',

#     }
# }
DATABASES = {
    'default': {
        'ENGINE': dj_database_url.config(conn_max_age=600, ssl_require=True)
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/


STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')

STATIC_URL = '/static/'

MEDIA_URL = '/images/'




MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL='/media/'



#Cloudinary COnfiguration
CLOUDINARY = {
  'cloud_name': 'gam1e4by',  
  'api_key': '758894869515971',  
  'api_secret': 'fqqHNbXb-ydqFGb4wONcbt2i4X4',  
}

#SMTP Configuration

EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST='smtp.gmail.com'
EMAIL_PORT=587
EMAIL_USE_TLS='TRUE'
EMAIL_HOST_USER='gamobyindia@gmail.com'
EMAIL_HOST_PASSWORD='flygamoby'

#AWS S3 BUCKET CONFIG

AWS_ACCESS_KEY_ID='AKIAXCEX4UOF6Z4DCXXG'
AWS_SECRET_ACCESS_KEY='LerQTFakezQTI7jCnjuOVLLLeYdmfG9pqh2DbEqA'
AWS_STORAGE_BUCKET_NAME='gamoby-fly'
AWS_S3_CUSTOM_DOMAIN = AWS_STORAGE_BUCKET_NAME + '.s3.ap-south-1.amazonaws.com'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
URL = 'https://' + AWS_STORAGE_BUCKET_NAME + '.s3.ap-south-1.amazonaws.com/'
MEDIA_ROOT='media'
MEDIA_URL = URL + 'media/'

DEFAULT_FILE_STORAGE = 'gamobysite.storage_backends.MediaStorage'
